help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf tmp dist .cache site .github/reports
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	git fetch --prune
	git gc --prune=now --aggressive

uv-install:  ## Install uv on your system
	curl -LsSf https://astral.sh/uv/install.sh | sh
	@echo 'export PATH="$$HOME/.local/bin:$$PATH"' >> ~/.bashrc
	@echo 'Installed uv, please re-open your bash terminal or zsh terminal.'

fmt: ## Run pre-commit hooks
	uvx pre-commit run -a

serve: ## Serve the skills site locally (http://0.0.0.0:9987)
	uv run zensical serve

build: ## Build the static site into ./site
	uv run zensical build
